Repository H2-AOAO/Android, pull requests merged in 2024-01, with the labels that each got.

#5 [FEATURE] 공룡 키우기 레이아웃 / 하단바 / 상점 레이아웃 생성
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/kr/sesac/aoao/android/MainActivity.kt
  app/src/main/java/kr/sesac/aoao/android/MarketActivity.kt
  app/src/main/java/kr/sesac/aoao/android/RaiseDinoActivity.kt
  app/src/main/java/kr/sesac/aoao/android/RecyclerViewAdapter_Market.kt
  app/src/main/java/kr/sesac/aoao/android/RecyclerViewAdapter_RaiseDino.kt
  app/src/main/java/kr/sesac/aoao/android/model/ItemData.kt
  app/src/main/res/drawable/design_gradient_background.xml
  app/src/main/res/drawable/design_round_shape.xml
  app/src/main/res/drawable/dino_background.png
  app/src/main/res/drawable/dino_blue_lv2.png
  app/src/main/res/drawable/dino_blue_lv3.png
  app/src/main/res/drawable/dino_blue_lv4.png
  app/src/main/res/drawable/dino_egg.png
  app/src/main/res/drawable/dino_egg_none.png
  app/src/main/res/drawable/dino_green_lv2.png
  app/src/main/res/drawable/dino_green_lv3.png
  app/src/main/res/drawable/dino_green_lv4.png
  app/src/main/res/drawable/dino_pink_lv2.png
  app/src/main/res/drawable/dino_pink_lv3.png
  app/src/main/res/drawable/dino_pink_lv4.png
  app/src/main/res/drawable/dino_purple_lv2.png
  app/src/main/res/drawable/dino_purple_lv3.png
  app/src/main/res/drawable/dino_purple_lv4.png
  app/src/main/res/drawable/dino_yellow_lv2.png
  app/src/main/res/drawable/dino_yellow_lv3.png
  app/src/main/res/drawable/dino_yellow_lv4.png
  app/src/main/res/drawable/icon_dino.png
  app/src/main/res/drawable/icon_dollar_white.png
  app/src/main/res/drawable/icon_dollar_yellow.png
  app/src/main/res/drawable/icon_friend.png
  app/src/main/res/drawable/icon_home.png
  app/src/main/res/drawable/icon_market.png
  app/src/main/res/drawable/icon_mypage.png
  app/src/main/res/drawable/icon_rewrite.png
  app/src/main/res/drawable/icon_todo.png
  app/src/main/res/drawable/item_food.png
  app/src/main/res/drawable/item_love.png
  app/src/main/res/drawable/item_medicine.png
  app/src/main/res/drawable/item_play.png
  app/src/main/res/drawable/item_set.png
  app/src/main/res/drawable/shadow_bottom_bar.png
  app/src/main/res/layout/activity_bottom_bar.xml
  app/src/main/res/layout/activity_market.xml
  app/src/main/res/layout/activity_raise_dino.xml
  app/src/main/res/layout/recycler_dino_item_button.xml
  app/src/main/res/layout/recycler_dino_market_item.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: 🐥 feat

#12 [FEATURE] 투두리스트 및 다이어리 스위칭 fragment 방식으로 변환
  app/src/main/java/kr/sesac/aoao/android/CalendarFragment.kt
  app/src/main/java/kr/sesac/aoao/android/DiaryFragment.kt
  app/src/main/java/kr/sesac/aoao/android/HomeActivity.kt
  app/src/main/java/kr/sesac/aoao/android/TodolistFragment.kt
  app/src/main/java/kr/sesac/aoao/android/model/TodayViewModel.kt
  app/src/main/res/drawable/todo_folder_list.png
  app/src/main/res/drawable/user_profile.png
  app/src/main/res/layout/activity_calendar.xml
  app/src/main/res/layout/fragment_calendar.xml
  app/src/main/res/layout/fragment_diary.xml
  app/src/main/res/layout/fragment_todolist.xml
Labels: 🐥 feat

#18 [FEATURE] 투두리스트 및 폴더 화면 레이아웃 구현
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/kr/sesac/aoao/android/HomeActivity.kt
  app/src/main/java/kr/sesac/aoao/android/TodolistFragment.kt
  app/src/main/java/kr/sesac/aoao/android/calendar/diary/ui/DiaryFragment.kt
  app/src/main/java/kr/sesac/aoao/android/calendar/todo/ui/RecyclerViewAdapter_Todo.kt
  app/src/main/java/kr/sesac/aoao/android/calendar/todo/ui/RecyclerViewAdapter_TodoFolder.kt
  app/src/main/java/kr/sesac/aoao/android/calendar/todo/ui/TodolistFragment.kt
  app/src/main/java/kr/sesac/aoao/android/calendar/ui/CalendarFragment.kt
  app/src/main/java/kr/sesac/aoao/android/calendar/ui/HomeActivity.kt
  app/src/main/java/kr/sesac/aoao/android/model/TodoData.kt
  app/src/main/java/kr/sesac/aoao/android/model/TodoFolderData.kt
  app/src/main/java/kr/sesac/aoao/android/model/TodoFoldersData.kt
  app/src/main/java/kr/sesac/aoao/android/todofolder/ui/RecyclerViewAdapter_Folder.kt
  app/src/main/java/kr/sesac/aoao/android/todofolder/ui/TodoFolderActivity.kt
  app/src/main/res/drawable/todo_checked_blue.png
  app/src/main/res/drawable/todo_checked_pink.png
  app/src/main/res/drawable/todo_checked_yellow.png
  app/src/main/res/drawable/todo_folder_add_button.png
  app/src/main/res/drawable/todo_folder_delete_button.png
  app/src/main/res/drawable/todo_folder_icon.png
  app/src/main/res/drawable/todo_folder_setting_button.png
  app/src/main/res/drawable/todo_folder_update_button.png
  app/src/main/res/drawable/todo_unchecked.png
  app/src/main/res/layout/activity_calendar.xml
  app/src/main/res/layout/activity_todo_folder.xml
  app/src/main/res/layout/bottom_sheet_dialog_todo.xml
  app/src/main/res/layout/fragment_todolist.xml
  app/src/main/res/layout/recycler_folder_item.xml
  app/src/main/res/layout/recycler_folder_todo_item.xml
  app/src/main/res/layout/recycler_todo_item.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: 🐥 feat

#20 [FEATURE] 투두리스트 항목 수정 및 삭제 기능 구현
  app/src/main/java/kr/sesac/aoao/android/calendar/todo/ui/RecyclerViewAdapter_Todo.kt
  app/src/main/java/kr/sesac/aoao/android/calendar/todo/ui/RecyclerViewAdapter_TodoFolder.kt
  app/src/main/java/kr/sesac/aoao/android/calendar/todo/ui/TodolistFragment.kt
  app/src/main/java/kr/sesac/aoao/android/model/TodoFolderData.kt
  app/src/main/java/kr/sesac/aoao/android/todofolder/ui/TodoFolderActivity.kt
Labels: 🐥 feat

#23 [FEAT] 친구 리스트 조회, 검색 기능 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/kr/sesac/aoao/android/friend/FriendActivity.kt
  app/src/main/java/kr/sesac/aoao/android/friend/model/FriendResponse.kt
  app/src/main/res/layout/activity_calendar.xml
  app/src/main/res/layout/activity_friend.xml
  app/src/main/res/layout/recycle_friend_item_list.xml
Labels: 🐥 feat

#26 [FEATURE] 아이템 관련 API 완성
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/kr/sesac/aoao/android/common/GlobalVarApp.kt
  app/src/main/java/kr/sesac/aoao/android/dino/service/DinoInfoService.kt
  app/src/main/java/kr/sesac/aoao/android/dino/ui/RaiseDinoActivity.kt
  app/src/main/java/kr/sesac/aoao/android/dino/ui/RecyclerViewAdapter_RaiseDino.kt
  app/src/main/java/kr/sesac/aoao/android/market/model/MarketResponse.kt
  app/src/main/java/kr/sesac/aoao/android/market/service/MarketService.kt
  app/src/main/java/kr/sesac/aoao/android/market/ui/MarketActivity.kt
  app/src/main/java/kr/sesac/aoao/android/market/ui/RecyclerViewAdapter_Market.kt
  app/src/main/java/kr/sesac/aoao/android/market/ui/RecyclerViewAdapter_UserItem.kt
  app/src/main/res/layout/activity_market.xml
  app/src/main/res/layout/activity_raise_dino.xml
  app/src/main/res/layout/recycler_dino_item_button.xml
  app/src/main/res/layout/recycler_dino_market_item.xml
  app/src/main/res/layout/recycler_dino_market_user_item.xml
  app/src/main/res/values/colors.xml
Labels: 🐥 feat

#30 [FEATURE] Token 이용해 user 관리
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/kr/sesac/aoao/android/MainActivity.kt
  app/src/main/java/kr/sesac/aoao/android/common/TokenManager.kt
  app/src/main/java/kr/sesac/aoao/android/user/model/ProfileResponse.kt
  app/src/main/java/kr/sesac/aoao/android/user/model/TokenResponse.kt
  app/src/main/java/kr/sesac/aoao/android/user/service/UserService.kt
  app/src/main/java/kr/sesac/aoao/android/user/ui/LoginActivity.kt
  app/src/main/java/kr/sesac/aoao/android/user/ui/MyPageActivity.kt
  app/src/main/java/kr/sesac/aoao/android/user/ui/SignUpActivity.kt
  app/src/main/res/drawable/logo.png
  app/src/main/res/drawable/user1.webp
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_my_page.xml
  app/src/main/res/layout/activity_sign_up.xml
  app/src/main/res/values/colors.xml
Labels: 🐥 feat

#31 [FEATURE] 새로운 다이노 만들기 및 하단바
  app/src/main/AndroidManifest.xml
  app/src/main/java/kr/sesac/aoao/android/MainActivity.kt
  app/src/main/java/kr/sesac/aoao/android/calendar/ui/HomeActivity.kt
  app/src/main/java/kr/sesac/aoao/android/common/BottomNavigationHandler.kt
  app/src/main/java/kr/sesac/aoao/android/dino/ui/NewDinoActivity.kt
  app/src/main/java/kr/sesac/aoao/android/dino/ui/RaiseDinoActivity.kt
  app/src/main/java/kr/sesac/aoao/android/friend/FriendActivity.kt
  app/src/main/res/drawable/background_new_dino.png
  app/src/main/res/drawable/bottom_bar_shape.xml
  app/src/main/res/drawable/bottom_bar_style.xml
  app/src/main/res/drawable/dino_color_list.png
  app/src/main/res/drawable/egg_rainbow.png
  app/src/main/res/drawable/icon_check.png
  app/src/main/res/layout/activity_bottom_bar.xml
  app/src/main/res/layout/activity_calendar.xml
  app/src/main/res/layout/activity_friend.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_new_dino.xml
  app/src/main/res/layout/activity_raise_dino.xml
  app/src/main/res/menu/bottom_navigation_menu.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: ⚙️ chore, 🐥 feat

#34 [FEATURE] 투두 폴더 관련 API 연결
  app/src/main/java/kr/sesac/aoao/android/calendar/diary/ui/DiaryFragment.kt
  app/src/main/java/kr/sesac/aoao/android/calendar/todo/ui/RecyclerViewAdapter_Todo.kt
  app/src/main/java/kr/sesac/aoao/android/calendar/todo/ui/RecyclerViewAdapter_TodoFolder.kt
  app/src/main/java/kr/sesac/aoao/android/calendar/todo/ui/TodolistFragment.kt
  app/src/main/java/kr/sesac/aoao/android/calendar/ui/CalendarFragment.kt
  app/src/main/java/kr/sesac/aoao/android/calendar/ui/HomeActivity.kt
  app/src/main/java/kr/sesac/aoao/android/common/RetrofitService.kt
  app/src/main/java/kr/sesac/aoao/android/common/ToastGenerator.kt
  app/src/main/java/kr/sesac/aoao/android/common/TokenManager.kt
  app/src/main/java/kr/sesac/aoao/android/dino/ui/RaiseDinoActivity.kt
  app/src/main/java/kr/sesac/aoao/android/market/ui/MarketActivity.kt
  app/src/main/java/kr/sesac/aoao/android/model/TodayData.kt
  app/src/main/java/kr/sesac/aoao/android/model/TodayViewModel.kt
  app/src/main/java/kr/sesac/aoao/android/model/TodoData.kt
  app/src/main/java/kr/sesac/aoao/android/model/TodoFolderData.kt
  app/src/main/java/kr/sesac/aoao/android/todofolder/model/request/FolderSaveRequest.kt
  app/src/main/java/kr/sesac/aoao/android/todofolder/model/request/FolderUpdateRequest.kt
  app/src/main/java/kr/sesac/aoao/android/todofolder/model/request/TodoSaveRequest.kt
  app/src/main/java/kr/sesac/aoao/android/todofolder/model/request/TodoUpdateRequest.kt
  app/src/main/java/kr/sesac/aoao/android/todofolder/model/response/FolderDetailResponse.kt
  app/src/main/java/kr/sesac/aoao/android/todofolder/model/response/FolderQueryDetailResponse.kt
  app/src/main/java/kr/sesac/aoao/android/todofolder/model/response/PaletteDetailResponse.kt
  app/src/main/java/kr/sesac/aoao/android/todofolder/model/response/PaletteQueryDetailResponse.kt
  app/src/main/java/kr/sesac/aoao/android/todofolder/model/response/TodoDetailResponse.kt
  app/src/main/java/kr/sesac/aoao/android/todofolder/model/response/TodoFolderDetailResponse.kt
  app/src/main/java/kr/sesac/aoao/android/todofolder/model/response/TodoQueryDetailResponse.kt
  app/src/main/java/kr/sesac/aoao/android/todofolder/service/PaletteService.kt
  app/src/main/java/kr/sesac/aoao/android/todofolder/service/TodoFolderRepository.kt
  app/src/main/java/kr/sesac/aoao/android/todofolder/service/TodoFolderService.kt
  app/src/main/java/kr/sesac/aoao/android/todofolder/service/TodoRepository.kt
  app/src/main/java/kr/sesac/aoao/android/todofolder/service/TodoService.kt
  app/src/main/java/kr/sesac/aoao/android/todofolder/ui/TodoFolderActivity.kt
  app/src/main/res/layout/activity_calendar.xml
  app/src/main/res/layout/activity_todo_folder.xml
  app/src/main/res/layout/fragment_calendar.xml
  app/src/main/res/values/colors.xml
Labels: 🐥 feat

#38 [FEATURE] 온보딩 페이지 제작
  app/src/main/AndroidManifest.xml
  app/src/main/java/kr/sesac/aoao/android/MainActivity.kt
  app/src/main/res/drawable/onboding_flower.png
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_sign_up.xml
Labels: 🐥 feat

#41 [FEATURE]다이노 기본 기능 완성
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/kr/sesac/aoao/android/MainActivity.kt
  app/src/main/java/kr/sesac/aoao/android/common/ErrorMessageGenerator.kt
  app/src/main/java/kr/sesac/aoao/android/common/GlobalVarApp.kt
  app/src/main/java/kr/sesac/aoao/android/common/RetrofitService.kt
  app/src/main/java/kr/sesac/aoao/android/dino/model/request/ExpRequset.kt
  app/src/main/java/kr/sesac/aoao/android/dino/model/request/ItemNumRequset.kt
  app/src/main/java/kr/sesac/aoao/android/dino/model/request/NewDinoRequest.kt
  app/src/main/java/kr/sesac/aoao/android/dino/model/response/DinoLvResponse.kt
  app/src/main/java/kr/sesac/aoao/android/dino/model/response/DinoResponse.kt
  app/src/main/java/kr/sesac/aoao/android/dino/model/response/UserItemResponse.kt
  app/src/main/java/kr/sesac/aoao/android/dino/service/DinoInfoService.kt
  app/src/main/java/kr/sesac/aoao/android/dino/service/DinoInfoUtil.kt
  app/src/main/java/kr/sesac/aoao/android/dino/service/NewDinoUtil.kt
  app/src/main/java/kr/sesac/aoao/android/dino/ui/DialogActivity.kt
  app/src/main/java/kr/sesac/aoao/android/dino/ui/NewDinoActivity.kt
  app/src/main/java/kr/sesac/aoao/android/dino/ui/RaiseDinoActivity.kt
  app/src/main/java/kr/sesac/aoao/android/dino/ui/RecyclerViewAdapter_RaiseDino.kt
  app/src/main/java/kr/sesac/aoao/android/market/model/MarketResponse.kt
  app/src/main/java/kr/sesac/aoao/android/market/model/request/UsePointRquest.kt
  app/src/main/java/kr/sesac/aoao/android/market/model/response/MarketResponse.kt
  app/src/main/java/kr/sesac/aoao/android/market/service/MarketService.kt
  app/src/main/java/kr/sesac/aoao/android/market/service/MarketUtil.kt
  app/src/main/java/kr/sesac/aoao/android/market/ui/MarketActivity.kt
  app/src/main/java/kr/sesac/aoao/android/market/ui/RecyclerViewAdapter_Market.kt
  app/src/main/java/kr/sesac/aoao/android/market/ui/RecyclerViewAdapter_UserItem.kt
  app/src/main/java/kr/sesac/aoao/android/todofolder/service/TodoFolderRepository.kt
  app/src/main/java/kr/sesac/aoao/android/todofolder/service/TodoRepository.kt
  app/src/main/res/drawable/logo.png
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_market.xml
  app/src/main/res/layout/activity_raise_dino.xml
  app/src/main/res/layout/dialog_dino_lv5.xml
  app/src/main/res/layout/recycler_dino_item_button.xml
  app/src/main/res/layout/recycler_dino_market_item.xml
  app/src/main/res/layout/recycler_dino_market_user_item.xml
  app/src/main/res/raw/firework_1.gif
  app/src/main/res/raw/firework_2.gif
  app/src/main/res/raw/firework_3.gif
  app/src/main/res/raw/moving_dino.gif
  app/src/main/res/values/colors.xml
  app/src/main/res/values/styles.xml
Labels: 🐥 feat

#47 [BUG] 깃 머지 실수 해결
  app/src/main/java/kr/sesac/aoao/android/common/GlobalVarApp.kt
  app/src/main/java/kr/sesac/aoao/android/dino/ui/PastDinoActivity.kt
  app/src/main/java/kr/sesac/aoao/android/dino/ui/RecyclerViewAdapter_pastDino.kt
  app/src/main/res/drawable/dino_background_without_sky.png
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_past_dino.xml
  app/src/main/res/layout/recycler_past_dino.xml
Labels: 🛠️ bug, 🐥 feat

#50 [FEATURE] 과거 다이노 페이지 완성
  app/src/main/AndroidManifest.xml
  app/src/main/java/kr/sesac/aoao/android/dino/model/response/PastDinoResponse.kt
  app/src/main/java/kr/sesac/aoao/android/dino/service/DinoInfoService.kt
  app/src/main/java/kr/sesac/aoao/android/dino/service/DinoInfoUtil.kt
  app/src/main/java/kr/sesac/aoao/android/dino/ui/PastDinoActivity.kt
  app/src/main/java/kr/sesac/aoao/android/dino/ui/RaiseDinoActivity.kt
  app/src/main/java/kr/sesac/aoao/android/dino/ui/RecyclerViewAdapter_pastDino.kt
  app/src/main/res/drawable/icon_past.png
  app/src/main/res/layout/activity_past_dino.xml
  app/src/main/res/layout/activity_raise_dino.xml
  app/src/main/res/layout/recycler_past_dino.xml
Labels: 🐥 feat

#56 [FEATURE] 투두리스트 폴더 수정 시 팔레트 색상 선택 기능 구현
  app/src/main/java/kr/sesac/aoao/android/calendar/todo/ui/RecyclerViewAdapter_Todo.kt
  app/src/main/java/kr/sesac/aoao/android/calendar/todo/ui/RecyclerViewAdapter_TodoFolder.kt
  app/src/main/java/kr/sesac/aoao/android/common/RetrofitConnection.kt
  app/src/main/java/kr/sesac/aoao/android/model/Palette.kt
  app/src/main/java/kr/sesac/aoao/android/model/PaletteData.kt
  app/src/main/java/kr/sesac/aoao/android/model/TodoFolderData.kt
  app/src/main/java/kr/sesac/aoao/android/todofolder/model/response/FolderQueryDetailResponse.kt
  app/src/main/java/kr/sesac/aoao/android/todofolder/model/response/PaletteQueryDetailResponse.kt
  app/src/main/java/kr/sesac/aoao/android/todofolder/model/response/TodoQueryDetailResponse.kt
  app/src/main/java/kr/sesac/aoao/android/todofolder/service/PaletteRepository.kt
  app/src/main/java/kr/sesac/aoao/android/todofolder/ui/RecyclerViewAdapter_Folder.kt
  app/src/main/java/kr/sesac/aoao/android/todofolder/ui/RecyclerViewAdapter_Palette.kt
  app/src/main/java/kr/sesac/aoao/android/todofolder/ui/TodoFolderActivity.kt
  app/src/main/res/drawable/todo_checked_blue.png
  app/src/main/res/drawable/todo_checked_green.png
  app/src/main/res/drawable/todo_checked_light_green.png
  app/src/main/res/drawable/todo_checked_mint.png
  app/src/main/res/drawable/todo_checked_orange.png
  app/src/main/res/drawable/todo_checked_purple.png
  app/src/main/res/drawable/todo_checked_red.png
  app/src/main/res/drawable/todo_checked_sky_blue.png
  app/src/main/res/layout/bottom_sheet_dialog_todo_folder.xml
  app/src/main/res/layout/recycler_palette_item.xml
Labels: ⭐️ refactor

#58 [FEATURE] 하단바 수정 및 다이노 마이페이지
  app/src/main/java/kr/sesac/aoao/android/common/BottomNavigationHandler.kt
  app/src/main/java/kr/sesac/aoao/android/user/ui/LoginActivity.kt
  app/src/main/java/kr/sesac/aoao/android/user/ui/MyPageActivity.kt
  app/src/main/java/kr/sesac/aoao/android/user/ui/SignUpActivity.kt
  app/src/main/res/drawable/button_border.xml
  app/src/main/res/drawable/icon_search.png
  app/src/main/res/drawable/icon_user.png
  app/src/main/res/layout/activity_calendar.xml
  app/src/main/res/layout/activity_friend.xml
  app/src/main/res/layout/activity_my_page.xml
  app/src/main/res/layout/activity_past_dino.xml
  app/src/main/res/layout/activity_raise_dino.xml
  app/src/main/res/layout/bottom_bar.xml
  app/src/main/res/layout/recycle_friend_item_list.xml
  app/src/main/res/menu/bottom_navigation_menu.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/styles.xml
Labels: ⚙️ chore, 🐥 feat

#60 [BUG] 생명주기 오류 픽스
  app/src/main/java/kr/sesac/aoao/android/calendar/ui/HomeActivity.kt
  app/src/main/java/kr/sesac/aoao/android/todofolder/ui/TodoFolderActivity.kt
Labels: 🛠️ bug

#61 [FEATURE] 다이어리 API 연결
  app/src/main/java/kr/sesac/aoao/android/calendar/diary/model/request/DiarySaveRequest.kt
  app/src/main/java/kr/sesac/aoao/android/calendar/diary/model/request/DiaryUpdateRequest.kt
  app/src/main/java/kr/sesac/aoao/android/calendar/diary/model/response/DiaryResponse.kt
  app/src/main/java/kr/sesac/aoao/android/calendar/diary/service/DiaryRepository.kt
  app/src/main/java/kr/sesac/aoao/android/calendar/diary/service/DiaryService.kt
  app/src/main/java/kr/sesac/aoao/android/calendar/diary/ui/DiaryFragment.kt
  app/src/main/java/kr/sesac/aoao/android/calendar/ui/CalendarFragment.kt
Labels: ⭐️ refactor

#69 [BUG] 투두 및 투두 폴더 관련 API 연결 수정
  app/src/main/java/kr/sesac/aoao/android/calendar/todo/ui/TodolistFragment.kt
  app/src/main/java/kr/sesac/aoao/android/model/PaletteData.kt
  app/src/main/java/kr/sesac/aoao/android/model/TodoFolderData.kt
  app/src/main/java/kr/sesac/aoao/android/todofolder/model/response/FolderDetailResponse.kt
  app/src/main/java/kr/sesac/aoao/android/todofolder/model/response/FolderQueryDetailResponse.kt
  app/src/main/java/kr/sesac/aoao/android/todofolder/model/response/FolderSaveResponse.kt
  app/src/main/java/kr/sesac/aoao/android/todofolder/model/response/TodoFolderDetailResponse.kt
  app/src/main/java/kr/sesac/aoao/android/todofolder/model/response/TodoQueryDetailResponse.kt
  app/src/main/java/kr/sesac/aoao/android/todofolder/model/response/TodoSaveResponse.kt
  app/src/main/java/kr/sesac/aoao/android/todofolder/service/TodoFolderRepository.kt
  app/src/main/java/kr/sesac/aoao/android/todofolder/service/TodoFolderService.kt
  app/src/main/java/kr/sesac/aoao/android/todofolder/service/TodoRepository.kt
  app/src/main/java/kr/sesac/aoao/android/todofolder/service/TodoService.kt
  app/src/main/java/kr/sesac/aoao/android/todofolder/ui/TodoFolderActivity.kt
Labels: 🛠️ bug

#72 [FEATURE] 프로필 편집 API 연결
  app/src/main/java/kr/sesac/aoao/android/user/service/UserService.kt
  app/src/main/java/kr/sesac/aoao/android/user/ui/NicknameActivity.kt
Labels: ⭐️ refactor

#73 [FEAT] 최종 업데이트
  app/src/main/AndroidManifest.xml
  app/src/main/dinosoul_launcher_icon-playstore.png
  app/src/main/java/kr/sesac/aoao/android/common/BottomNavigationHandler.kt
  app/src/main/java/kr/sesac/aoao/android/user/ui/PasswordEditActivity.kt
  app/src/main/java/kr/sesac/aoao/android/user/ui/ProfileEditActivity.kt
  app/src/main/res/drawable-hdpi/dinosoul_icon.png
  app/src/main/res/drawable-mdpi/dinosoul_icon.png
  app/src/main/res/drawable-xhdpi/dinosoul_icon.png
  app/src/main/res/drawable-xxhdpi/dinosoul_icon.png
  app/src/main/res/drawable-xxxhdpi/dinosoul_icon.png
  app/src/main/res/font/main_font.xml
  app/src/main/res/font/soyomaple.otf
  app/src/main/res/font/soyomaplebold.otf
  app/src/main/res/layout/activity_calendar.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_market.xml
  app/src/main/res/layout/activity_my_page.xml
  app/src/main/res/layout/activity_new_dino.xml
  app/src/main/res/layout/activity_nickname.xml
  app/src/main/res/layout/activity_password_edit.xml
  app/src/main/res/layout/activity_past_dino.xml
  app/src/main/res/layout/activity_profile_edit.xml
  app/src/main/res/layout/activity_raise_dino.xml
  app/src/main/res/layout/activity_sign_up.xml
  app/src/main/res/layout/activity_todo_folder.xml
  app/src/main/res/layout/bottom_sheet_dialog_todo.xml
  app/src/main/res/layout/bottom_sheet_dialog_todo_folder.xml
  app/src/main/res/layout/dialog_dino_lv5.xml
  app/src/main/res/layout/fragment_calendar.xml
  app/src/main/res/layout/fragment_diary.xml
  app/src/main/res/layout/recycler_dino_item_button.xml
  app/src/main/res/layout/recycler_dino_market_item.xml
  app/src/main/res/layout/recycler_dino_market_user_item.xml
  app/src/main/res/layout/recycler_folder_item.xml
  app/src/main/res/layout/recycler_folder_todo_item.xml
  app/src/main/res/layout/recycler_past_dino.xml
  app/src/main/res/layout/recycler_todo_item.xml
  app/src/main/res/menu/bottom_navigation_menu.xml
  app/src/main/res/mipmap-anydpi-v26/dinosoul_launcher_icon.xml
  app/src/main/res/mipmap-anydpi-v26/dinosoul_launcher_icon_round.xml
  app/src/main/res/mipmap-hdpi/dinosoul_launcher_icon.webp
  app/src/main/res/mipmap-hdpi/dinosoul_launcher_icon_foreground.webp
  app/src/main/res/mipmap-hdpi/dinosoul_launcher_icon_round.webp
  app/src/main/res/mipmap-mdpi/dinosoul_launcher_icon.webp
  app/src/main/res/mipmap-mdpi/dinosoul_launcher_icon_foreground.webp
  app/src/main/res/mipmap-mdpi/dinosoul_launcher_icon_round.webp
  app/src/main/res/mipmap-xhdpi/dinosoul_launcher_icon.webp
  app/src/main/res/mipmap-xhdpi/dinosoul_launcher_icon_foreground.webp
  app/src/main/res/mipmap-xhdpi/dinosoul_launcher_icon_round.webp
  app/src/main/res/mipmap-xxhdpi/dinosoul_launcher_icon.webp
  app/src/main/res/mipmap-xxhdpi/dinosoul_launcher_icon_foreground.webp
  app/src/main/res/mipmap-xxhdpi/dinosoul_launcher_icon_round.webp
  app/src/main/res/mipmap-xxxhdpi/dinosoul_launcher_icon.webp
  app/src/main/res/mipmap-xxxhdpi/dinosoul_launcher_icon_foreground.webp
  app/src/main/res/mipmap-xxxhdpi/dinosoul_launcher_icon_round.webp
  app/src/main/res/values/dinosoul_launcher_icon_background.xml
  app/src/main/res/values/font_style.xml
  app/src/main/res/values/styles.xml
Labels: ⚙️ chore, 🐥 feat

#75 [CHORE] 개인 코드 점검
  app/src/main/java/kr/sesac/aoao/android/common/BottomNavigationHandler.kt
  app/src/main/java/kr/sesac/aoao/android/common/ErrorMessageGenerator.kt
  app/src/main/java/kr/sesac/aoao/android/common/RetrofitConnection.kt
  app/src/main/java/kr/sesac/aoao/android/common/RetrofitService.kt
  app/src/main/java/kr/sesac/aoao/android/dino/service/DinoInfoService.kt
  app/src/main/java/kr/sesac/aoao/android/dino/service/DinoInfoUtil.kt
  app/src/main/java/kr/sesac/aoao/android/dino/service/NewDinoUtil.kt
  app/src/main/java/kr/sesac/aoao/android/dino/ui/DialogActivity.kt
  app/src/main/java/kr/sesac/aoao/android/dino/ui/NewDinoActivity.kt
  app/src/main/java/kr/sesac/aoao/android/dino/ui/PastDinoActivity.kt
  app/src/main/java/kr/sesac/aoao/android/dino/ui/RaiseDinoActivity.kt
  app/src/main/java/kr/sesac/aoao/android/dino/ui/RecyclerViewAdapter_RaiseDino.kt
  app/src/main/java/kr/sesac/aoao/android/dino/ui/RecyclerViewAdapter_pastDino.kt
  app/src/main/java/kr/sesac/aoao/android/market/service/MarketService.kt
  app/src/main/java/kr/sesac/aoao/android/market/ui/MarketActivity.kt
  app/src/main/java/kr/sesac/aoao/android/market/ui/RecyclerViewAdapter_Market.kt
  app/src/main/java/kr/sesac/aoao/android/market/ui/RecyclerViewAdapter_UserItem.kt
  app/src/main/java/kr/sesac/aoao/android/todofolder/ui/RecyclerViewAdapter_Checked.kt
  app/src/main/res/layout/activity_my_page.xml
  app/src/main/res/layout/activity_new_dino.xml
  app/src/main/res/layout/activity_password_edit.xml
  app/src/main/res/layout/activity_raise_dino.xml
  app/src/main/res/layout/bottom_bar.xml
  app/src/main/res/layout/dialog_dino_lv5.xml
  app/src/main/res/layout/recycler_checked_palette_item.xml
  app/src/main/res/layout/recycler_past_dino.xml
Labels: ⚙️ chore

#77 [FEATURE] 투두리스트 및 폴더 관련 주석 추가
  app/src/main/java/kr/sesac/aoao/android/calendar/todo/ui/RecyclerViewAdapter_Todo.kt
  app/src/main/java/kr/sesac/aoao/android/calendar/ui/HomeActivity.kt
  app/src/main/java/kr/sesac/aoao/android/todofolder/ui/TodoFolderActivity.kt
  app/src/main/res/layout/activity_home.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_todo_folder.xml
  app/src/main/res/layout/bottom_sheet_dialog_todo.xml
  app/src/main/res/layout/bottom_sheet_dialog_todo_folder.xml
  app/src/main/res/layout/fragment_todolist.xml
  app/src/main/res/layout/recycler_folder_item.xml
  app/src/main/res/layout/recycler_folder_todo_item.xml
  app/src/main/res/layout/recycler_palette_item.xml
  app/src/main/res/layout/recycler_todo_item.xml
Labels: ⚙️ chore, ⭐️ refactor
